### PR TITLE
Changes needed for Windows compatibility

### PR DESCRIPTION
**Pull request by welcheb**

### CODE REVIEW

**Comment by hansenms** [comment]
Does this compile with Visual Studio or cygwin or something else. How did you deal with the xslt stuff?

**Comment by welcheb** [comment]
Hi Michael,

I just sent you an email as you emailed me. Please let me know if there are more details you need to know.

I am compiling on Windows using Visual Studio Pro 2010. I can also create the executable at the command line using cl.exe with a command like this:

cl main.cpp pugixml.cpp /EHa /Fephilips_to_ismrmrd.exe /GS /TP /W3 /Zc:wchar_t- /Gm- /O2 /Ob2 /D “ IN32" /D "_WINDOWS" /D "NDEBUG" /D "_WIN32" /D "UNICODE" /D "_UNICODE" /D "_CRT_SECURE_NO_WARNINGS" /D "__func__=**FUNCTION**" /WX- /Zc:forScope /Gd /MD /I"C:/Libraries/iconv-1.9.2.win32/include/" /I"C:/Libraries/libxml2-2.6.30+.win32/include/" /I"C:/Libraries/boost/boost_1_55_0_x86/" /I"C:/Libraries/libxml2-2.6.30+.win32/include/" /I"C:/Libraries/libxslt-1.1.26.win32/include/" /I"C:/Libraries/install/ismrmrd_x86/include/" /link /libpath:"C:/Libraries/libxml2-2.6.30+.win32/lib/" libxml2.lib /libpath:"C:/Libraries/libxslt-1.1.26.win32/lib/" libxslt.lib /libpath:"C:/Libraries/install/ismrmrd_x86/lib/" ismrmrd.lib /libpath:"C:/Libraries/boost/boost_1_55_0_x86/lib32-msvc-12.0/" /DYNAMICBASE "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib" /VERBOSE

The main change was to compile everything including ismrmrd as 32-bit. I can prepare an update to the README.md page to explain the Windows steps.

Most importantly, the code still compiles on Mac.
- Brian

**Comment by hansenms** [comment]
Sounds good. I will merge this. The easiest path forward on Windows may be cygwin and GCC.

**Comment by welcheb** [comment]
Thanks Michael!
- B

**Pull request merged**
